modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="MIT License"
[[mods]] #mandatory
modId="sizeshiftingpotions" #mandatory
version="1.1.1"
issueTrackerURL=""
displayName="Size Shifting Potions" #mandatory
logoFile="icon.png"
authors="UltrusMods, Calamitous_End" #optional
description='''Adds shrinking and growing potions to the game!'''
[[dependencies.sizeshiftingpotions]] #optional
# the modid of the dependency
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[37,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.sizeshiftingpotions]] #optional
# the modid of the dependency
modId="pehkui" #mandatory
mandatory=true #mandatory
versionRange="[3,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.sizeshiftingpotions]]
modId="minecraft"
mandatory=true
versionRange="[1.17,)"
ordering="NONE"
side="BOTH"